name: Scheduled Merge Remote Action
# from https://github.com/marketplace/actions/fork-sync-with-upstream
on:
  schedule:
    - cron: '0 7 * * 1,4'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Pull (Fast-Forward) upstream changes
        run: git remote add upstream https://github.com/checkstyle/checkstyle \
          && git pull --ff-only upstream master && git push

